# Generated by Django 4.0.5 on 2022-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countermodel',
            name='number',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
