# Generated by Django 4.0.5 on 2022-06-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0002_alter_countermodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countermodel',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
